source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'NativeAdvancedExample' do
  pod 'Google-Mobile-Ads-SDK'
  
  platform :ios, '8.0'

  #Note: default is using NativeAd Framework
  #pod 'MintegralAdSDK'
  #Note: or
  #pod 'MintegralAdSDK/NativeAd'

  #Note: using Bid NativeAd Framework
  #pod 'MintegralAdSDK/BidNativeAd'


  #Note: using RewardVideoAd Framework
  pod 'MintegralAdSDK/RewardVideoAd'

  #Note: using Bid RewardVideoAd Framework
  pod 'MintegralAdSDK/BidRewardVideoAd'

  #Note: using InterstitialVideoAd Framework
  pod 'MintegralAdSDK/InterstitialVideoAd'

  #Note: using Bid InterstitialVideoAd Framework
  pod 'MintegralAdSDK/BidInterstitialVideoAd'

  #Note: using InterstitialAd Framework
  pod 'MintegralAdSDK/InterstitialAd'

  #Note: using InterActiveAd Framework
  pod 'MintegralAdSDK/InterActiveAd'

  #Note: using BannerAd Framework
  pod 'MintegralAdSDK/BannerAd'

  #Note: using Bid BannerAd Framework
  pod 'MintegralAdSDK/BidBannerAd'
end
